export const typeColors: Record<string, string> = {
  normal: "border-gray-400",
  fire: "border-orange-500",
  water: "border-blue-500",
  electric: "border-yellow-400",
  grass: "border-green-500",
  ice: "border-cyan-300",
  fighting: "border-red-700",
  poison: "border-purple-500",
  ground: "border-amber-600",
  flying: "border-indigo-300",
  psychic: "border-pink-500",
  bug: "border-lime-500",
  rock: "border-stone-500",
  ghost: "border-violet-700",
  dragon: "border-indigo-700",
  dark: "border-stone-700",
  steel: "border-slate-400",
  fairy: "border-pink-300",
}
